name: MapManager
main: org.inventivetalent.mapmanager.MapManagerPlugin
author: inventivetalent
version: ${project.version}
api-version: '1.13'

softdepend: [PacketListenerApi]

commands:
  mapmanager:
    aliases: [mmanager]